# Persistent volume and claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ao-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ao-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

# Crossref metadata secret
---
apiVersion: v1
kind: Secret
metadata:
  name: crossref-metadata
  namespace: default
type: Opaque
data:
  api-key: c2VjcmV0 # 'secret'
