services:
  http-server:
    build:
      context: .
      dockerfile: http-server-Dockerfile
    image: ao-tests-http-server
    ports:
      - "5080:5080"
    network_mode: bridge

  ftp-server:
    build:
      context: .
      dockerfile: ftp-server-Dockerfile
    image: ao-tests-ftp-server
    ports:
      - "5021:5021"
      - "30000-30009:30000-30009"
    network_mode: bridge
